### ISSUE TITLE
Migration to rapidsms 0.11

### ISSUE THREAD

**Issue by miclovich** [nyaruka/nsms#5]
Can we have nsms "automation" tested/migrated with/to the newer rapidsms? It sure is still a handy tool (nsms).

**Comment by nicpottier** [comment]
Hi Victor,

We are considering it, not positive what route we will take.  What features do you find useful?

-Nic

**Comment by miclovich** [comment]
Hi Nic;
the features I find useful:
- ease at which bootstrapping a rapidsms project is made
- very organic handling of template (template variables) and injection in SMS (via `app.py`)
- handling of translation

-Vic
